matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - sh prepare-sketch.sh
      script:
        - sh increment-version.sh
        - sh inject-version.sh
        - sh build-sketch.sh

    - language: csharp
      before_script:
        - git checkout $TRAVIS_BRANCH
        - sh prepare.sh
        - sh init.sh
      script:
        - sh increment-version.sh
        - sh inject-version.sh
        - sh build.sh

