version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Prepare
          command: apt-get install -y sudo

      - run:
          name: Setup
          command: sh prepare.sh

